[package]
name = "llanite"
version = "0.1.0"
edition = "2021"
authors = [ "Ben McAvoy <Ben.Mcavoy@tutanota.com>" ]
license = "MIT"
homepage = "https://github.com/Llanite/Llanite"
repository = "https://github.com/Llanite/Llanite"
description = "A layered game engine wrote for performance and flexibility."

[dependencies]
ecs_rust = "0.0.4"
pollster = "0.3.0"
tracing = "0.1.37"
wgpu = "0.17.0"
winit = "0.28.6"

[dependencies.tracing-subscriber]
version = "0.3.17"
features = [ "tracing-log" ]

[lib]
name = "llanite"
path = "src/lib.rs"

[profile.release]
codegen-units = 1
strip = true
lto = true
